### ISSUE TITLE
Default constructor and first type is int can throw NullReferenceException

### ISSUE THREAD

**Issue by MrGroovy** [mcintyre321/OneOf#11]
The following throws a NullReferenceException:

    var x = new OneOf<int, bool>();
    int m = x.Match(
        i => 1,
        b => 2);

Solution In the Get<T> function?

    return value == null
        ? default(T)
        : (T)value;

**Comment by gps035** [comment]
I don't believe this is the intended way to use the library, a OneOf instance should be created implicitly like the following. The constructor would preferably be private, but C# structs require a public parameterless constructor. 
```csharp
OneOf<int, bool> x = 1;
```
That said, this shouldn't throw an exception, and it will when the first type argument is any value type.

Your suggested solution would work. I happen to have a branch that would solve this problem as well (https://github.com/gps035/OneOf/tree/avoid-boxing-on-backing-fields). I've been meaning clean this up and do a few pull requests, but since installing VS 2017 RC, I've been unable to build any .NET Core code.

**Comment by MrGroovy** [comment]
I agree one should not use the parameterless constructor. But it can not be prevented. And indeed it should not throw a NullReferenceException.

**Comment by mcintyre321** [comment]
Maybe a `OneOfNotCreatedCorrectlyException`* should be thrown if `this.index < 0 || this.index > this.arity` ? 

* better name welcome

At some point I was planning to update it to have `value0` ... `valueN` fields to prevent boxing/unboxing against the `object value` field, so if anyone is going to send a PR, it would be great to have that too!

**Comment by MrGroovy** [comment]
Could also assume the first type and use the default value for that type. Eliminates the possibility of a exception, this is what i would prefer.

**Comment by gps035** [comment]
I can try to make pull request to make the change you mentioned @mcintyre321. I have a laptop that should be able to build it still. I would get a chance later in the day.
That change would cause the backing fields to have the default values @MrGroovy , so it would solve that problem. If it is decided to add an exception for this case, it could be added separately, but I don't think it would be necessary.

**Comment by mcintyre321** [comment]
Thanks @gps035 , that would be great.

@MrGroovy I think it would (currently) be a bad idea to write code that uses that ctor and then tries to depend on the behaviour of that OneOf struct. I'm of two minds about whether an error should be thrown when you try to Match on it. Defaulting to `default(T0)` might surprise some people.

**Comment by NickStrupat** [comment]
The solution is to set all indexes to 1 more than they are now (T0 would be index: 1, etc.), because calling the parameterless constructor or using `default`/`default(TOneOf)` will result in a zeroed instance of `TOneOf`.

An index of 0 means the calling code called either the parameterless constructor or used something like `default`. That can be handled when switching/matching by throwing something like a `OneOfUninitializedException`.
