### ISSUE TITLE
Problems with implicit cast

### ISSUE THREAD

**Issue by ChrisLambrou** [mcintyre321/OneOf#25]
I've run into scenario involving an implicit cast that I expected to work, but which produces a compiler error. Here's a test case:

```c#
[Test]
public void ImplicitCasts()
{
    OneOf<string, int> a = 123;
    OneOf<string, int> b = "abc";
    OneOf<IEnumerable<string>, int> c = 123;
    OneOf<IEnumerable<string>, int> d = new string[0];
    OneOf<IEnumerable<string>, int> e = (IEnumerable<string>) new string[0];
}
```

The first four statements are fine, but the fifth statement causes the following compiler error:
 _error CS0029: Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<string>' to 'OneOf.OneOf<System.Collections.Generic.IEnumerable<string>, int>'_.

Any thoughts? Do you think the cast should work? It's particularly puzzling me why the fourth statement is fine.

**Comment by gps035** [comment]
This appears to be an edge case in the language, rather than an issue with `OneOf`. The following code gives a similar error at compile time. 
```csharp
class Program
{
    static void Main(string[] args)
    {
        Wrapper<IEnumerable<string>> wrapperB = (IEnumerable<string>) new[] { "Hello, World!" };
        Console.WriteLine(wrapperB.Data.First());
        Console.ReadLine();
    }
}

class Wrapper<T>
{
    public T Data { get; }
    public Wrapper(T data) => Data = data;
    public static implicit operator Wrapper<T>(T data) => new Wrapper<T>(data);
}
```
The only difference is that instead of `CS0029`, I am getting `CS0266	Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<string>' to 'Test.Wrapper<System.Collections.Generic.IEnumerable<string>>'. An explicit conversion exists (are you missing a cast?`.
Though, adding the suggested cast just results in an `InvalidCastException` in this case.
Converting the `Wrapper` class into a struct, we see the same behaviour as `OneOf`

This seems to happen whenever the generic parameter of the class is an interface. I've not had time to fully digest why, but the answers can probably be found in [this blog post](https://johnkoerner.com/csharp/why-does-this-implicit-conversion-fail/), and the [linked Stack Overflow question](https://stackoverflow.com/questions/9229928/more-on-implicit-conversion-operators-and-interfaces-in-c-sharp-again/9231325).

Good effort finding this one. I normally find it's best to limit my use of implicit conversions, so this is not a part of the language I have had a chance to read into until now.

**Comment by mcintyre321** [comment]
Unfortunately you can't do implicit operatiors on interface types, but you can do this:

```
OneOf<IEnumerable<string>, int> e = OneOf<IEnumerable<string>, int>.FromT0(new string[0]);
```

**Comment by ChrisLambrou** [comment]
Ah, that's a shame. I don't really agree with the thinking behind this:

> Why? Because one has the reasonable expectation that when one converts a value to an interface, that you are testing whether the object in question implements the interface, not asking for an entirely different object that implements the interface.

That seems to be general argument against all custom implicit casts, yet the feature exists in the language, nonetheless. Alas, it's not my language, so I don't get to make the rules, just live by them.

Thanks for digging into this further. :)

**Comment by mcintyre321** [comment]
I can imagine that the rules for resolving which implicit cast to use could get pretty hairy. Although they already can if you have `OneOf<Foo, Bar, object>` where `Foo : Bar`...

**Comment by layouttransition** [comment]
I reached the answer https://test-suiteneglected.github.io/encodeuricomponent/
