### ISSUE TITLE
Considering Option helper

### ISSUE THREAD

**Issue by mcintyre321** [mcintyre321/OneOf#43]
Hello watchers! I'm considering adding an `Option` helper, so that 

```
OneOf<Foo, None> Get(string id){
        var foo = _repository.Query<Foo>(id).SingleOrDefault();
        if (foo == null) return new None();
	return foo;
}
```
can be written as 
```
OneOf<Foo, None> Get(string id){
	return Option.Of(_repository.Query<Foo>(id).SingleOrDefault());
}
```
Implementation would look something like:
```
public static class Option
{
	public static OneOf<T, None> Of<T>(T? item) where T : struct  => (item.HasValue) ? (OneOf<T, None>) item : new None();

	public static OneOf<T, None> Of<T>(T item) where T: class => (item == null) ? (OneOf<T, None>) new None() : item;
}
```

Any feedback welcome.

**Comment by mcintyre321** [comment]
Maybe I should have a special `OptionOf<T>` (a la https://github.com/mcintyre321/OneOf/issues/35), because using one guarantees that the T is not null... hmm... and then there's the question of whether this is needed in our non-nullable c# 8 futureworld...

**Comment by bartelink** [comment]
I'd call that `Option.Create` absent of any naming strategies in this repo. (Yes in F# it's called `Option.ofObj`)
Also perhaps make a `.ToOption()` extension method ?

**Comment by rtkelly13** [comment]
I think the better approach in regards to this would be interop with other projects that have a much more comprehensive option type such as https://github.com/nlkl/Optional making.
I'd say it's one of those things it these helpers are going to be put in place you need a whole wave of useful utility methods like Map, FlatMap (Bind), Iter(Tee), Plus Enumerable extensions like SingleOrNone() instead of SingleOrDefault() and many more that have been covered by Optional.

**Comment by rtkelly13** [comment]
I have written a wrapper around OneOf to implement Option<T>, Result<T> Getting the API right is a bit of a challenge.
https://github.com/Resultful/Resultful 

Having it in a separate package would be better too, The API could be subject to change and seeing as keeping OneOf small is a previously stated goal. Having separate release schedules etc would solve a lot of those issues.

I always conflict with the provided OneOf.Types even though it would be a breaking change separating them out would solve a lot of interop problems. May break that out into an issue, but would be a 3.X release if desired.

**Comment by mcintyre321** [comment]
Cheers folks.

@bartelink thanks for the F# version - I think I'd like to keep it pretty close to that behaviour, less surprising that way. I actually quite like how close `Option.Of` is to `Option.ofObj`

I'm not a fan of libraries which add extension methods to `object` (which are pretty core to the  "Optional" library) as I think it pollutes intellisense too much.

I'm still pretty torn about whether it should be a type of it's own or not though... @rtkelly13 what do you see as the _functional_ difference between an `Option` and `OneOf<T, None>` type? Are there capabilities a OneOf<T, None> lacks?

**Comment by mcintyre321** [comment]
```
[<AllowNullLiteral>] 
type public MyClass(reasonForLiving:string) =
    member x.ReasonForLiving with get() = reasonForLiving
let foo : MyClass = null
let opt = Option.ofObj(foo)
opt.IsNone.Dump(); //True

let opt2 = Option.Some(foo)
opt2.IsNone.Dump(); //False, so there's no absolute guarantee a Some option is notnever null
```

**Comment by bartelink** [comment]
> @bartelink thanks for the F# version - I think I'd like to keep it pretty close to that behaviour, less surprising that way. I actually quite like how close `Option.Of` is to `Option.ofObj`

I get that, but remember there's `Tuple.Create` and many other such things (not sure if there is a `Lazy.Create` or whether I always chuck it in my helpers)
 
> I'm not a fan of libraries which add extension methods to `object` (which are pretty core to the "Optional" library) as I think it pollutes intellisense too much.

Wasn't thinking; Good point, 100% agree

If this lib is going to have a `Result`, it can/should have an `Option`, to my mind.

I'm personally not a fan of dropping much functional stuff, i.e. the other helpers a la Optional into C# code (then again, my F# is heavy on `match` statements for processing `option`s; it's kinder on me and non Math Geek humans)

**Comment by rtkelly13** [comment]
There are very few differences, I think it all just points to the lack of type aliasing in C# makes it a problem because in  F# ```Option<T>``` is an alias of ```OneOf<T, None>``` essentially. I'd say it's more of an ergonomic thing the type signatures get a bit large in C# if you had something like ```Task<IEnumerable<OneOf<SomeAwfullyNamedCSharpClasssResult, None>>>```  writing that everywhere isn't the greatest, ```Task<IEnumerable<Option<SomeAwfullyNamedCSharpClasssResult>>``` isn't much better.

**Comment by rtkelly13** [comment]
> I'm personally not a fan of dropping much functional stuff, i.e. the other helpers a la Optional into C# code (then again, my F# is heavy on match statements for processing options; it's kinder on me and non Math Geek humans)

`Map`/`FlatMap` are a key part of the whole proposition of an Option type and the functional approach in general. For simple union types such as Option, Result. The match statement would be a fallback for me when a pre-existing functionality isn't present. Plus many of the concepts are wholey applicable when using LINQ as a reference point with a List being `0..*` and Option being `0..1`,  `Select`/`SelectMany` are methods on any `T[]` 

Without it, the C# 8 nullable reference types would result in shorter/clearer code. Due to `T?` being de-referenced to `T` when a null check has been performed/ in the right scope.  It's just not generally applicable only specific to the `Nullable<T>` type. 

F# also makes the functional stuff less necessary because of computation expressions.

> I'm not a fan of libraries which add extension methods to object (which are pretty core to the "Optional" library) as I think it pollutes intellisense too much.

Having the Some method as an extension method on T is a style choice and can pollute intellisense.
One solution to this is to isolate the Extension methods from the main namespace of the Lib in question. I conceed that this could be a fundamental issue to many and should be considered whenever adding extension methods to types that aren't your own. I've never particularly thought of it as an issue though as it aids discoverability.

**Comment by mcintyre321** [comment]
So we have `MapT0` already, perhaps I need to add `OneOf<T0, ..., TN> FlatMapT0(Func<T0, OneOf<T0, ..., TN>> map)` to the core lib?

**Comment by rtkelly13** [comment]
Honestly, I regret `MapTX` its useful in some scenarios but the name is meaningless because you have to look at the type you are mapping from to have any idea what the input is. 

I did have a go at that when discussing this issue.
https://github.com/mcintyre321/OneOf/issues/36. 
But seeing as I now think `MapTX` was a mistake adding FlatMap would compound this issue further.

Avoiding category theory entirely, there are a bunch of types where `FlatMap` makes sense like Option, Result  List, Task etc but they don't apply to the Union type that models them, you implement a `FlatMap/Bind` function for each of them like F# does. 

The Choice type which models the Union type in F# doesn't implement Map or Bind
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.choice%5b't1,'t2,'t3,'t4%5d-union-%5bfsharp%5d

**Comment by mcintyre321** [comment]
> but the name is meaningless because you have to look at the type you are mapping from to have any idea what the input is.

Do you mean the code is unreadable? You can specify type explicitly there:
	`var z = y.MapT0((int x) => x.ToString());`
} 

Interestingly, it seems if I take the T0/T1 off map:
	
e.g.
```
public static class MapExt
{

	public static OneOf<TOut, T1> Map<TOut, T0, T1>(this OneOf<T0, T1> oneOf, Func<T0, TOut> map)
	{
		return oneOf.Match(o => (OneOf<TOut, T1>)map(o), t1 => t1);
	}

	public static OneOf<T0, TOut> Map<TOut, T0, T1>(this OneOf<T0, T1> oneOf, Func<T1, TOut> map)
	{
		return oneOf.Match(o => (OneOf<T0, TOut>) o, t1 => map(t1));
	}
}
```
then it won't compile UNLESS the lambda specifies the type:

```
var z = y.Map((int x) => x.ToString());
var a = z.Map((string o) => int.Parse(o));

```

I'm quite tempted to 1. remove the MapT methods, and add Map/FlatMap in a second assembly

**Comment by rtkelly13** [comment]
That might be the best option going forward worth going through our original discussions as to why I settled on `MapTX` I think it was to solve ambiguity issues.
But it may not have been enough of an issue to warrant the poorer API.

Maybe move the extra OneOf.Types into a OneOf.Extensions package also, if you are going to put all these useful utilities in one place. I'd be quite keen on that change especially if there are going to be extension methods that will aid with the usage of those types. Would be a breaking change but the extra lib could move at a different pace to the core OneOf lib which should be much more stable once the breaking change has been made.

**Comment by mcintyre321** [comment]
Closing as the conversation has run dry, although I'm still intrigued by it
