### ISSUE TITLE
Conversion from OneOf<A, B> to OneOf<B, A> and similar

### ISSUE THREAD

**Issue by shoe-diamente** [mcintyre321/OneOf#56]
The notion of a discriminated union usually doesn't make a difference between `union X = A | B` and `union X = B | A`. Therefore it seems to me that the followings should be implicitly convertible:
 - A -> OneOf<A, B>
 - OneOf<A, B> -> OneOf<B, A>

Moreover this would be beneficial:
 - OneOf<A, B> -> OneOf<A, B, C>

Is there any way in which this could be implemented other than enumerate all the possible combinations? Or how could this be implemented? Should this be implemented?

**Comment by mcintyre321** [comment]
As C# doesn't enforce that the lambdas in the .Switch and .Match arguments include the parameter types in the source code, this would be quite dangerous! Swapping a `OneOf<A, B>` for a `OneOf<B, A>` as a return parameter could introduce surprise behaviour elsewhere in a project.

**Comment by shoe-diamente** [comment]
I'm not sure I understand.
> As C# doesn't enforce that the lambdas in the .Switch and .Match arguments include the parameter types in the source code

But it does. The signature enforces that. Are you talking about the case of `OneOf<A, A>`?

**Comment by Jehoel** [comment]
I've figured this out, I'll post it as a new issue because my use-case was for allowing "widening" operations (e.g. from `OneOf<String,Int32>` to `OneOf<String,Int32,Int64>` without needing to generate conversion operations for all type-argument permutations.

**Comment by Jehoel** [comment]
I thought I had a solution to this by adding an `IHas<T>` (allowing direct access to `T`, possibly with an index argument) and having `OneOf<T0,T1> : IHas<T0>, IHas<T1>` (etc for `T0...Tn`) but it turns out that the C# 7 compiler will complain about "types may unify" and block _open_ generic types from implementing the same interface with different type parameters.

I want to see if I could build it in CIL directly with `ilasm` as it's a C# restriction and (as far as I know) not a restriction that's built-in to the CLI.
